### ISSUE TITLE
will there be a version for modx 2.3?

### ISSUE THREAD

**Issue by andreborud** [freelancewebdev/xodus#7]
just wondering if there will be an update for modx 2.3? Its s really good plugin and would be nice to have on the newer version of modx.

**Comment by matdave** [comment]
+1

**Comment by matdave** [comment]
https://github.com/matdave/xodus pretty simple fixes really.  I just updated the "getfile.class.php" in both core/components/xodus/controllers/ and core/components/xodus/processors/mgr/xodus/

**Comment by freelancewebdev** [comment]
I've merged @matdave's changes (thanks for that!), repackaged and republished so you should be able to get Xodus 1.0-pl with 2.3.x support from the repo.
